name: mpfi
channels:
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - xarray
  - numpy
  - scipy
  - plotly
  - pandas
  - pingouin
  - natsort
  - tqdm
  - ipykernel
  - yaml
  - scikit-image
  - netcdf4
  - h5netcdf
  - nbformat=5.10.4
  - pyarrow
  - conda-forge::python-kaleido
  - ipywidgets
  - jupyter
  - dask
  - zarr=3.0.6
