name: mpfi
channels:
  - conda-forge
dependencies:
  - xarray
  - numpy
  - scipy
  - plotly
  - pandas
  - natsort
  - tqdm
  - jupyter
  - yaml
  - scikit-image
  - netcdf4
  - nbformat=5.10.4
  - pyarrow
  - python-kaleido
  - ipywidgets
  - dask
  - zarr>=3.0.6
